Repository khulnasoft/coverage-ai, pull requests merged in 2024-07, with the labels that each got.

#27 Add C++ templated test
  README.md
  templated_tests/cpp_cli/.gitignore
  templated_tests/cpp_cli/CMakeLists.txt
  templated_tests/cpp_cli/Dockerfile
  templated_tests/cpp_cli/README.md
  templated_tests/cpp_cli/build_and_test_with_coverage.sh
  templated_tests/cpp_cli/calculator.cpp
  templated_tests/cpp_cli/calculator.hpp
  templated_tests/cpp_cli/main.cpp
  templated_tests/cpp_cli/test_calculator.cpp
  tests_integration/test_all.sh
  tests_integration/test_with_docker.sh
Labels: enhancement, Tests, Review effort [1-5]: 4

#33 Create tsconfig.json
  coverage_ai/CoverageProcessor.py
  coverage_ai/version.txt
  templated_tests/typescript_calculator/.gitignore
  templated_tests/typescript_calculator/Dockerfile
  templated_tests/typescript_calculator/README.md
  templated_tests/typescript_calculator/package-lock.json
  templated_tests/typescript_calculator/package.json
  templated_tests/typescript_calculator/src/index.html
  templated_tests/typescript_calculator/src/index.ts
  templated_tests/typescript_calculator/src/modules/Calculator.ts
  templated_tests/typescript_calculator/src/styles.scss
  templated_tests/typescript_calculator/tests/Calculator.test.ts
  templated_tests/typescript_calculator/tsconfig.json
  tests/test_CoverageProcessor.py
  tests_integration/increase_coverage.py
  tests_integration/test_all.sh
  tests_integration/test_with_docker.sh
Labels: configuration changes, Review effort [1-5]: 1

#34 Update UnitTestGenerator.py
  coverage_ai/CoverageAi.py
  coverage_ai/PromptBuilder.py
  coverage_ai/UnitTestGenerator.py
  coverage_ai/utils.py
  tests/test_AICaller.py
  tests/test_CoverageAi.py
  tests/test_CoverageProcessor.py
  tests/test_FilePreprocessor.py
  tests/test_PromptBuilder.py
  tests/test_ReportGenerator.py
  tests/test_Runner.py
  tests/test_UnitTestGenerator.py
  tests/test_load_yaml.py
  tests/test_main.py
  tests_integration/increase_coverage.py
Labels: documentation, enhancement, Review effort [1-5]: 2
